#!/usr/bin/env python

""" show assetnumbers from printers
By Mathias Decker
contact: mathias.decker@mdc-berlin.de
         github@mathiasdecker.de

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

def inventory_apc_inrow_AlarmConditionsTableSize(checkname, info):
   inventory = []
   for Assetnumber in info:
      inventory.append( ("Alarms", None) )
   return inventory

def check_apc_inrow_AlarmConditionsTableSize(item, params, info):
   count = info [0][0]
   if int(count) == 1:
      return (2, count + " alarm")    
   if int(count) > 1:
      return (2, count + " alarms")
   return (0, count + " alarms")
         
check_info["apc_inrow_AlarmConditionsTableSize"] = (check_apc_inrow_AlarmConditionsTableSize, "%s", 1, inventory_apc_inrow_AlarmConditionsTableSize)
snmp_info["apc_inrow_AlarmConditionsTableSize"] = ( ".1.3.6.1.4.1.318.1.1.13.3.1.1", [ "0" ] )
