#!/usr/bin/env python

""" lists all configured shares of a sun open storage box
By Mathias Decker
contact: mathias.decker@mdc-berlin.de
         github@mathiasdecker.de

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

check_includes['netapp_failed_disks'] = [ "df.include" ]

def inventory_netapp_failed_disks(info):
   inventory = []
   for message in info:
      inventory.append( ("Failed Disk(s)", {}) )
   return inventory

def check_netapp_failed_disks(item, params, info):
   for message in info:
      if message[0] == "There are no failed disks.":
         return (0, message[0])
      else:
         return (2, message[0])

check_info["netapp_failed_disks"] = (check_netapp_failed_disks, "%s", 1, inventory_netapp_failed_disks)
snmp_info["netapp_failed_disks"] = ( ".1.3.6.1.4.1.789.1.6.4", ["10"] )

