#!/usr/bin/env python

""" list poweredon and if they are pingable
By Mathias Decker
contact: mathias.decker@mdc-berlin.de
         github@mathiasdecker.de

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

def inventory_vSphere_PoweredOnWindowsClients(info):
   inventory = []
   for line in info:
      inventory.append( (line[0],"",None) )
   return inventory

def check_vSphere_PoweredOnWindowsClients(item, params, info):
   import os
   for line in info:
      if line[0] == item:
         ip = line[1]

         critC = 0
         critM = ""
	 if line[2] == "PoweredOn":
            if ip == "None":
               warnC = warnC + 1
               warnM = warnM + " (!!) virtual desktop does not have an ip address  "
            else:
               run = "/usr/local/nagios/libexec/check_icmp -n 1 -H "
               run += ip
	       ping = os.popen(run).read()
	       if ping.split(" - ")[0] != "OK":
	          critC = critC + 1
	          critM += ping.split(" - ")[1]
            if critC > 0:
               return (2, "".join(("CRIT - (!!) virtual desktop is not pingable at ",ip," - the firewall might block icmp packets, please check that")))
            return(0,"".join(("OK - virtual desktop is pingable at ",ip)))
	 else:
	    return(0,"OK - virtual desktop is currently powered off or suspended")
            
   return (3, "looks like virtual desktop has been removed")

# declare the check to Check_MK
check_info['vSphere_PoweredOnWindowsClients'] = (check_vSphere_PoweredOnWindowsClients, "vdesktop_%s", 0, inventory_vSphere_PoweredOnWindowsClients)
