#!/bin/bash
for i in $(docker inspect --format='{{.Name}};{{.State.Running}};{{.Image}}' $(docker ps -a -q --no-trunc) | cut -c2-)
do
        name=$(echo $i | cut -f1 -d';')
        state=$(echo $i | cut -f2 -d';')
        image=$(echo $i | cut -f3 -d';')
        if [ "$state" == "true" ]
        then
                echo "0 container_$name c= OK - container $name is running with image $image"
        else
                echo "2 container_$name c= OK - container $name is not running"
        fi
done
