#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# this check is based on check_mk/apc_inrow_temp
# modified to work with ACRP5xx devices
# By Mathias Decker
# contact: mathias.decker@mdc-berlin.de
#          github@mathiasdecker.de
#
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.
"""
	airIRRP500UnitStatusOperateMode				SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.1.0
  	airIRRP500UnitStatusMaximumRackInletTempUS		SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.2.0
  	airIRRP500UnitStatusMaximumRackInletTempMetric		SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.3.0
  	airIRRP500UnitStatusSupplyAirTempUS			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.4.0
  	airIRRP500UnitStatusSupplyAirTempMetric			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.5.0
  	airIRRP500UnitStatusReturnAirTempUS			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.6.0
  	airIRRP500UnitStatusReturnAirTempMetric			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.7.0
  	airIRRP500UnitStatusSupplyHumidity			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.8.0
  	airIRRP500UnitStatusReturnHumidity			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.9.0
  	airIRRP500UnitStatusAirFlowUS				SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.10.0
  	airIRRP500UnitStatusAirFlowMetric			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.11.0
  	airIRRP500UnitStatusFanSpeed				SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.12.0
  	airIRRP500UnitStatusCoolDemand				SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.13.0
  	airIRRP500UnitStatusCoolOutput				SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.14.0
  	airIRRP500UnitStatusHumidifyDemand			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.15.0
  	airIRRP500UnitStatusHumidifyOutput			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.16.0
  	airIRRP500UnitStatusDehumidifyDemand			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.17.0
  	airIRRP500UnitStatusDehumidifyOutput			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.18.0
  	airIRRP500UnitStatusReheatDemand			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.19.0
  	airIRRP500UnitStatusReheatOutput			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.20.0
  	airIRRP500UnitStatusInputState				SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.21.0
  	airIRRP500UnitStatusOutputState				SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.22.0
  	airIRRP500UnitStatusRackInletTemperature1US		SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.23.0
  	airIRRP500UnitStatusRackInletTemperature1Metric		SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.24.0
  	airIRRP500UnitStatusRackInletTemperature2US		SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.25.0
  	airIRRP500UnitStatusRackInletTemperature2Metric		SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.26.0
  	airIRRP500UnitStatusRackInletTemperature3US		SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.27.0
  	airIRRP500UnitStatusRackInletTemperature3Metric		SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.28.0
  	airIRRP500UnitStatusContainmtDPUS			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.29.0
  	airIRRP500UnitStatusContainmtDPMetric			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.30.0
  	airIRRP500UnitStatusFilterDPUS				SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.31.0
  	airIRRP500UnitStatusFilterDPMetric			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.32.0
  	airIRRP500UnitStatusHumidifierCurrent			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.33.0
  	airIRRP500UnitStatusHumidifierWaterConductivity		SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.34.0
  	airIRRP500UnitStatusActivePowerSource			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.35.0
  	airIRRP500UnitStatusFluidValvePosition			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.36.0
  	airIRRP500UnitStatusFluidFlowUS				SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.37.0
  	airIRRP500UnitStatusFluidFlowMetric			SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.38.0
  	airIRRP500UnitStatusEnteringFluidTemperatureUS		SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.39.0
  	airIRRP500UnitStatusEnteringFluidTemperatureMetric	SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.40.0
  	airIRRP500UnitStatusLeavingFluidTemperatureUS		SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.41.0
  	airIRRP500UnitStatusLeavingFluidTemperatureMetric	SCALAR	read-only	INTEGER	1.3.6.1.4.1.318.1.1.13.3.3.2.2.2.42.0
"""

def apc_inrow_rp_temp_convert(info):
    vars = [
            "Rack Inlet 1",
            "Rack Inlet 2",
            "Rack Inlet 3",
            "Supply Air",
            "Return Air",
            "Entering Fluid",
            "Leaving Fluid",
            ]
    count = 0
    data = {}
    for name in vars:
        if info != "-1":
            value = saveint(info[count])
            data[name] = value / 10.0
        count += 1
    return data

apc_inrow_rp_temp_default_levels = ( 30, 35 )
def inventory_apc_inrow_rp_temp(info):
    info = apc_inrow_rp_temp_convert(info[0])
    return [ (x, "apc_inrow_rp_temp_default_levels") for x in info.keys() ]

def check_apc_inrow_rp_temp(item, params, info):
    info = apc_inrow_rp_temp_convert(info[0])
    for sensor, value in info.items():
        if sensor == item:
            warn, crit = params
            levels = " (Warning/Critical at %.2f/%2f°C)" % ( warn, crit)
            message = "Current: %.2f°C" % value
            perf = [ ('temp', value, warn, crit ) ]
            if value > crit:
                return 2, message + levels, perf
            if value > warn:
                return 1, message + levels, perf
            return 0, message, perf

    return 3, "Sensor not found"

check_info["apc_inrow_rp_temp"] = {
    "check_function"        : check_apc_inrow_rp_temp,
    "inventory_function"    : inventory_apc_inrow_rp_temp,
    "service_description"   : "Temperature %s",
    "group"                 : "hw_temperature",
    "snmp_info"             : (".1.3.6.1.4.1.318.1.1.13.3.3.2.2.2", [ 24, 26, 28, 5, 7, 40, 42 ]),
    "snmp_scan_function"    : lambda oid: oid(".1.3.6.1.2.1.1.2.0") == ".1.3.6.1.4.1.318.1.3.14.7",
    "has_perfdata"          : True,
}

