#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# ails.  You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

# Author: Lars Michelsen <lm@mathias-kettner.de>
# Modified for Dell PowerConnect 10GbE Switchs by: Mathias Decker <mathias.decker@mdc-berlin.de>

# Relevant SNMP OIDs:
#.1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4.9 = STRING: "    5 Secs (  4.180%)   60 Secs (  3.6352%)  300 Secs (  3.7350%)"

# Default values for parameters that can be overriden.
dell_powerconnect_10g_cpu_default_levels = (80, 90)

# Inventory of dell power connect CPU details.
def inventory_dell_powerconnect_10g_cpu(checkname, info):
    return [ (None, 'dell_powerconnect_10g_cpu_default_levels') ]

# Check of dell power connect CPU details.
def check_dell_powerconnect_10g_cpu(item, params, info):
    p = re.compile('5 Secs \( {0,2}(([0-9]|[0-9][0-9]|[0-9][0-9][0-9])\.[0-9]+)%\)[ ]+60 Secs \( {0,2}(([0-9]|[0-9][0-9]|[0-9][0-9][0-9])\.[0-9]+)%\)[ ]+300 Secs \( {0,2}(([0-9]|[0-9][0-9]|[0-9][0-9][0-9])\.[0-9]+)%\)')
    m = p.search(info[0][0])    
    onesecondperc = float(m.group(1))
    oneminuteperc = float(m.group(3))
    fiveminutesperc = float(m.group(5))

    cpu_util = saveint(onesecondperc)
    if cpu_util >= 0 <= 100:
        status = 0
        output = ''
        if cpu_util >= params[1]:
            status = 2
            output = ' (Above %d%%)' % params[1]
        elif cpu_util >= params[0]:
            status = 1
            output = ' (Above %d%%)' % params[0]

        # Darn. It again happend. Someone mixed up load and utilization.
        # We do *not* rename the performance variables here, in order not
        # to mix up existing RRDs...
        return (status, 'CPU utilization is %d%% (1 min: %d%% / 5 min: %d%%) %s' % (onesecondperc, oneminuteperc, fiveminutesperc, output),
               [('load', '%d%%' % cpu_util, params[0], params[1], 0, 100),
                ('loadavg 60s', '%d%%' % saveint(oneminuteperc), params[0], params[1], 0, 100),
                ('loadavg 5m', '%d%%' % saveint(fiveminutesperc), params[0], params[1], 0, 100),
               ])

    return (3, "Invalid  information in SNMP data")

# Auto-detection of CPU elements.

check_info["dell_powerconnect_10g_cpu"] = {
    'check_function':          check_dell_powerconnect_10g_cpu,
    'inventory_function':      inventory_dell_powerconnect_10g_cpu,
    'service_description':     'CPU utilization',
    'has_perfdata':            True,
    'snmp_info':               ('.1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4', ['9']),
    'snmp_scan_function':      \
     lambda oid: ".1.3.6.1.4.1.674.10895" in oid(".1.3.6.1.2.1.1.2.0"),
}
