#!/usr/bin/env python

""" show assetnumbers from printers
By Mathias Decker
contact: mathias.decker@mdc-berlin.de
         github@mathiasdecker.de

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

def inventory_hp_assetnumbers(checkname, info):
   inventory = []
   lineIndex = 0
   for Assetnumber in info:
      line = str(lineIndex) 
      inventory.append( ("Assetnumber", None) )
      lineIndex = lineIndex + 1
   return inventory

def check_hp_assetnumbers(item, params, info):
   assetnumber = info [0][0]
   assetnumber = assetnumber[2:]
   return (0, assetnumber)
         
check_info["hp_assetnumbers"] = (check_hp_assetnumbers, "%s", 1, inventory_hp_assetnumbers)
snmp_info["hp_assetnumbers"] = ( ".1.3.6.1.4.1.11.2.3.9.4.2.1.1.3.12", [ "0" ] )
