#!/usr/bin/env python

""" disk status of suns 351x storage boxes
By Mathias Decker
contact: mathias.decker@mdc-berlin.de
         github@mathiasdecker.de

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

def inventory_sun_351x(checkname, info):
   inventory = []
   for line in info:
      if line[2] == "4094":
         inventory.append( (line[0],"",None) )
   return inventory

def check_sun_351x(item, params, info):
   for line in info:
      if item == line[0]:
         drive = "drive (" + line[3] + ")"
         if line[1] == '0':
            return (2, "WARN - new " + drive + " found - not configured yet")
         if line[1] == '1':
            return (0, "OK - " + drive + " is fine")
         if line[1] == '2':
            return (1, "WARN - used " + drive + " found")
         if line[1] == '3':
            return (0, "OK - spare " + drive + " found")
         if line[1] == '4':
            return (1, "WARN - " + drive + " initializing")
         if line[1] == '5':
            return (1, "WARN - " + drive + " rebuilding")
         if line[1] == '6':
            return (1, "WARN - adding " + drive + " to logical drive")
         if line[1] == '9':
            return (0, "OK - global spare " + drive + " found")
         if line[1] == '17':
            return (1, "WARN - " + drive + " cloning")
         if line[1] == '18':
            return (1, "WARN - " + drive + " is a valid clone")
         if line[1] == '19':
            return (1, "WARN - " + drive + " copying")
         if line[1] == '63':
            return (2, "CRIT - " + drive + " absent")
         if line[1] == '252':
            return (2, "CRIT - missing global spare " + drive + "")
         if line[1] == '253':
            return (2, "CRIT - missing spare " + drive + "")
         if line[1] == '254':
            return (2, "CRIT - missing " + drive + "")
         if line[1] == '255':
            return (2, "CRIT - failed " + drive + "")

   return (3, "UNKNOWN - not yet implemented")

check_info["sun_351x"] = (check_sun_351x, "Disk %s", 1, inventory_sun_351x)
snmp_info["sun_351x"] = ( ".1.3.6.1.4.1.42.2.180.3510.1.1.6.1", [ "4", "11", "14", "15" ] )

