#!/usr/bin/env python

""" lists all configured shares of a sun open storage box
By Mathias Decker
contact: mathias.decker@mdc-berlin.de
         github@mathiasdecker.de

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

check_includes['sunstorage_shares'] = [ "df.include" ]

def inventory_sunstorage_shares(info):
   inventory = []
   for sharename, size, used, subproject in info:
      inventory.append( ("Share " + sharename, {}) )
   return inventory

def check_sunstorage_shares(item, params, info):
   for sharename, size, used, subproject in info:
      if "Share " + sharename == item:
         size_mb = float(size) * 1024.0
         avail_mb = (float(size) - float(used)) * 1024.0
         state, infotext, perfdata = df_check_filesystem_single(g_hostname, item, size_mb, avail_mb, 0,0, params)
         return (0, "OK - [" + subproject + "] " + sharename + " is at " + infotext ,perfdata)
   return (3, "Share seems to be deleted")

check_info["sunstorage_shares"] = (check_sunstorage_shares, "%s", 1, inventory_sunstorage_shares)
snmp_info["sunstorage_shares"] = ( ".1.3.6.1.4.1.42.2.225.1.6.1", ["5","7","8","4"] )
snmp_scan_functions["sunstorage_shares"] = lambda oid: oid(".1.3.6.1.4.1.42.2.225.1.4.2.0") == "Sun ZFS Storage 7320" or oid(".1.3.6.1.4.1.42.2.225.1.4.2.0") == "Sun Storage 7110"  or oid(".1.3.6.1.4.1.42.2.225.1.4.2.0") == "Sun ZFS Storage 7420"

