#!/usr/bin/env python

""" lists trend micro client-server connections
By Mathias Decker
contact: mathias.decker@mdc-berlin.de
         github@mathiasdecker.de

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

def inventory_trendmicro_connections(info):
   inventory = []
   inventory.append(("trendmicro_connections",None,None))
   return inventory

def check_trendmicro_connections(item, params, info):
   import time
   counter = 0
   hosts = ""
   for line in info:
      if (int(line[0])+900) > int(time.time()):
         counter = counter + 1
         hosts += line[2] + " | "
   if counter > 0:
      return (2, "CRITICAL - " + str(counter) + " officescan clients online (within the last 15 Minutes) - move them to the new server [" + hosts + "]" )
   else:
      return (0, "OK - nothing to do (" + str(len(info)) + " connections found)")

check_info['trendmicro_connections'] = (check_trendmicro_connections, "", 0, inventory_trendmicro_connections)
